name: WakaTime Stats

on:
  schedule:
    - cron: "0 0 * * *" # Обновление каждую ночь в полночь
  workflow_dispatch: # Позволяет запускать вручную

jobs:
  update-readme:
    name: Update WakaTime Stats
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          BLOCKS: "▓▒░" # Стиль закраски полосок прогресса
          SHOW_TIME: true
          SHOW_MASKED_TIME: false
